import datetime
print(datetime.date.today())
print("Your personal information will be needed to register a Gmail account")
print("Enter your name")
name=input()
print("Welcome ",name)
print("Enter your age")
age=input()
print("Hello",name),print("Aged:",age)
print("Which school are you studying in?")
school=input()
print("Which grade are you?")
grade=input()
print("What class are you in?")
class_name=input()
print("**Pls verify your personal information**:\nName:",name+"\nAge:",age+"\nSchool:",school+"\nGrade:",grade+"\nClass:",class_name)
print("Is it correct,incorrect or partially incorrect")
response=input()
print("Thanks!You will receive a mail to your school for the update of your gmail account :)")